site_name: Arctic
site_description: Arctic is a pluggable streaming lakehouse service layer on top of hive and iceberg

docs_dir: '../../docs/ch'
site_dir: '../../generated/ch'
remote_name: arctic-site
use_directory_urls: true
repo_url: https://github.com/NetEase/arctic
repo_name: NetEase/arctic
edit_uri: ""

# pip install mkdocs-material
theme:
  font:
    text: Msyh
  name: material
  language: zh
  favicon: images/favicon.ico
  logo: images/arctic_banner.png
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github

extra:
  search:
    language: 'en'
  alternate:
    - name: 中文
      link: /ch/
      lang: zh
    - name: English
      link: /en/
      lang: en

copyright: "Copyright 2018-2021"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Overview: index.md
  - Motivation: arctic-motivation.md
  - Quickstart: docker-quickstart.md
  - Table Format:
    - Tablestore: table-format/table-store.md
    - Iceberg Format: table-format/iceberg-format.md
    - Hive Format: table-format/hive-format.md
  - Meta Service:
    - Arctic Dashboard: meta-service/dashboard.md
    - Table Management: meta-service/table-management.md
    - Table Config: meta-service/table-properties.md
  - Optimizers: optimizers.md
  - Flink:
    - Getting Started: flink/flink-get-started.md
    - Flink DDL: flink/flink-ddl.md
    - Flink DML: flink/flink-dml.md
    - Flink DIM: flink/flink-dim.md
    - Flink DataStream: flink/flink-ds.md
    - Using Kafka as Logstore: flink/hidden-kafka.md
    - Flink CDC to Arctic: flink/flink-cdc-to-arctic.md
  - Spark:
    - Getting Started: spark/spark-get-started.md
    - Spark Configuration: spark/spark-conf.md
    - Spark DDL: spark/spark-ddl.md
    - Spark DML: spark/spark-dml.md
    - Spark DataFrame: spark/spark-dataframe.md
  - Trino: trino.md
  - Benchmark: benchmark.md
  - Roadmap: roadmap.md
  - How to contribute: contribute.md


plugins:
  - search

extra_css:
  - stylesheets/extra.css
